---

- name: Removes wordpress container
  docker_container:
    name: my_wordpress
    image: wordpress
    state: absent

- name: Create wordpress container
  docker_container:
    name: my_wordpress
    image: wordpress
    state: started
    volumes:
      - /home/ubuntu/wp:/usr/src/wordpress
    env:
      WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    ports:
      - "80:80"
