---

- name: Create wordpress container
  docker_container:
    name: my_wordpress
    image: wordpress
    state: started
    env:
      WORDPRESS_DB_HOST: WORDPRESS_DB_HOST: "{{ wordpress_db_host }}"
      WORDPRESS_DB_USER: test_user
      WORDPRESS_DB_PASSWORD: testingpassword
    ports:
      - "80:80"
